# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [7]:
import os
import numpy as np
import pandas as pd

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [62]:
print([n for n in range (1,51)])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [61]:
print([n for n in range (1,202) if n % 2 == 0])

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]

### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [21]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

In [60]:
print([list(i) for i in a])

[[0.84062117000000003, 0.48006451999999999, 0.78763260000000002, 0.77109654000000005], [0.44409792999999997, 0.090145160000000002, 0.81835917000000002, 0.87645455999999999], [0.7066597, 0.096108730000000003, 0.41247947000000001, 0.57433389000000001], [0.29960807, 0.42315023000000002, 0.34452557, 0.47510350000000001], [0.17003562999999999, 0.46843997999999998, 0.92796257999999998, 0.69814653999999998], [0.41290051, 0.19561070999999999, 0.16284783, 0.97016248000000005], [0.71725408000000002, 0.87702738000000002, 0.31244594999999997, 0.76615487000000004], [0.20754036000000001, 0.57871812, 0.072140679999999999, 0.40356048], [0.12149553, 0.53222417, 0.9976855, 0.12536346000000001], [0.80930099, 0.50962848999999999, 0.94555126, 0.33364762999999997]]

### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [58]:
print([x for i in a for x in i if x>=0.5])

[0.84062117000000003, 0.78763260000000002, 0.77109654000000005, 0.81835917000000002, 0.87645455999999999, 0.7066597, 0.57433389000000001, 0.92796257999999998, 0.69814653999999998, 0.97016248000000005, 0.71725408000000002, 0.87702738000000002, 0.76615487000000004, 0.57871812, 0.53222417, 0.9976855, 0.80930099, 0.50962848999999999, 0.94555126]

### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [63]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])

In [64]:
print([d for x in b for i in x for d in i])

[0.55867166000000001, 0.062107919999999997, 0.081472970000000006, 0.82579068, 0.91512477999999997, 0.068330340000000003, 0.054406339999999997, 0.65857692999999995, 0.30296619000000002, 0.067698330000000001, 0.96031862999999995, 0.51293743000000003, 0.091432150000000004, 0.71893381999999995, 0.45850679, 0.58256463999999997, 0.59005653999999996, 0.56266457000000003, 0.71600293999999998, 0.87392665999999997, 0.11434044, 0.86946679999999998, 0.65669312999999996, 0.10708681, 0.075296840000000004, 0.46470767000000002, 0.47984544000000001, 0.65368638000000001, 0.14901286, 0.23760687999999999]

### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [72]:
print([x[-1] for c in b for x in c if x[-1]<=0.5])

[0.081472970000000006, 0.068330340000000003, 0.30296619000000002, 0.45850679, 0.11434044, 0.10708681, 0.47984544000000001, 0.23760687999999999]

### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [78]:
print([i for i in os.listdir("../data") if ".csv" in i])

['sample_file_4.csv', 'sample_file_3.csv', 'sample_file_0.csv', 'sample_file_2.csv', 'sample_file_8.csv', 'sample_file_5.csv', 'sample_file_6.csv', 'sample_file_1.csv', 'sample_file_7.csv', 'sample_file_9.csv']

### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [94]:
import glob


df = pd.concat(map(pd.read_csv, glob.glob("../data/*.csv")))
display (df.head(10))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.901381,0.790944,0.596603,0.354721,0.357002,0.321325,0.738398,0.777885,0.775623,0.717817,0.788198,0.962214,0.394465,0.878922,0.084206,0.680941,0.992897,0.267455,0.212403,0.572150
1,0.763823,0.537281,0.708804,0.975269,0.053777,0.957740,0.389137,0.689829,0.510885,0.737445,0.097678,0.242906,0.073603,0.497591,0.798467,0.789078,0.947559,0.631497,0.057953,0.060306
2,0.571864,0.386243,0.567476,0.509283,0.552594,0.173807,0.229092,0.257945,0.313437,0.418311,0.750007,0.604759,0.234886,0.832337,0.421263,0.455785,0.893841,0.726412,0.458360,0.048740
3,0.956168,0.422274,0.121713,0.685208,0.713370,0.416245,0.337151,0.570693,0.435938,0.360098,0.037437,0.167545,0.847880,0.773456,0.490628,0.544232,0.954668,0.567280,0.571539,0.560742
4,0.121826,0.237479,0.553956,0.173660,0.354423,0.532080,0.271361,0.766006,0.607020,0.197302,0.526352,0.676571,0.473574,0.953228,0.413186,0.957242,0.642558,0.351496,0.547297,0.177401
0,0.376101,0.896590,0.500995,0.381416,0.447730,0.048472,0.094235,0.986890,0.582352,0.037230,0.130306,0.766153,0.153783,0.199140,0.330318,0.969657,0.110998,0.033474,0.117277,0.213938
1,0.498192,0.565500,0.152394,0.284232,0.557042,0.417095,0.663465,0.158188,0.039182,0.543442,0.521210,0.993481,0.580359,0.765757,0.931264,0.336841,0.271230,0.509798,0.877048,0.310951
2,0.635284,0.247512,0.179986,0.468231,0.911799,0.764209,0.941413,0.808370,0.578024,0.181267,0.064788,0.924226,0.070744,0.704575,0.948127,0.971452,0.360861,0.074394,0.386949,0.396453
3,0.647497,0.072412,0.681403,0.977189,0.690953,0.829347,0.236915,0.406938,0.898234,0.513575,0.532473,0.790312,0.082292,0.850821,0.088025,0.289218,0.822775,0.515933,0.962827,0.026952
4,0.170792,0.586900,0.029834,0.921923,0.090727,0.592746,0.972429,0.774760,0.293800,0.956949,0.811740,0.525562,0.454788,0.848812,0.095214,0.415311,0.026496,0.513342,0.830389,0.931145

### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [110]:
print([i for i in range (len(ls)) if df.median()[i]<0.48])

[2, 9, 12, 14, 17]

### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [109]:
df["20"]=df["19"]-0.1
display(df.head(10))

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.901381,0.790944,0.596603,0.354721,0.357002,0.321325,0.738398,0.777885,0.775623,0.717817,...,0.962214,0.394465,0.878922,0.084206,0.680941,0.992897,0.267455,0.212403,0.572150,0.472150
1,0.763823,0.537281,0.708804,0.975269,0.053777,0.957740,0.389137,0.689829,0.510885,0.737445,...,0.242906,0.073603,0.497591,0.798467,0.789078,0.947559,0.631497,0.057953,0.060306,-0.039694
2,0.571864,0.386243,0.567476,0.509283,0.552594,0.173807,0.229092,0.257945,0.313437,0.418311,...,0.604759,0.234886,0.832337,0.421263,0.455785,0.893841,0.726412,0.458360,0.048740,-0.051260
3,0.956168,0.422274,0.121713,0.685208,0.713370,0.416245,0.337151,0.570693,0.435938,0.360098,...,0.167545,0.847880,0.773456,0.490628,0.544232,0.954668,0.567280,0.571539,0.560742,0.460742
4,0.121826,0.237479,0.553956,0.173660,0.354423,0.532080,0.271361,0.766006,0.607020,0.197302,...,0.676571,0.473574,0.953228,0.413186,0.957242,0.642558,0.351496,0.547297,0.177401,0.077401
0,0.376101,0.896590,0.500995,0.381416,0.447730,0.048472,0.094235,0.986890,0.582352,0.037230,...,0.766153,0.153783,0.199140,0.330318,0.969657,0.110998,0.033474,0.117277,0.213938,0.113938
1,0.498192,0.565500,0.152394,0.284232,0.557042,0.417095,0.663465,0.158188,0.039182,0.543442,...,0.993481,0.580359,0.765757,0.931264,0.336841,0.271230,0.509798,0.877048,0.310951,0.210951
2,0.635284,0.247512,0.179986,0.468231,0.911799,0.764209,0.941413,0.808370,0.578024,0.181267,...,0.924226,0.070744,0.704575,0.948127,0.971452,0.360861,0.074394,0.386949,0.396453,0.296453
3,0.647497,0.072412,0.681403,0.977189,0.690953,0.829347,0.236915,0.406938,0.898234,0.513575,...,0.790312,0.082292,0.850821,0.088025,0.289218,0.822775,0.515933,0.962827,0.026952,-0.073048
4,0.170792,0.586900,0.029834,0.921923,0.090727,0.592746,0.972429,0.774760,0.293800,0.956949,...,0.525562,0.454788,0.848812,0.095214,0.415311,0.026496,0.513342,0.830389,0.931145,0.831145

### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.

In [121]:
print([i for i in df.values.flatten() if i>0.7 and i<0.75])

[0.73839820369832787, 0.71781667059579279, 0.70880423629168177, 0.73744491817494917, 0.72641211145380014, 0.7133695725698419, 0.70457501129597544, 0.73475108521287968, 0.73430923140011373, 0.74906808181834772, 0.73903129271113122, 0.71592902651579116, 0.70339304095807087, 0.70136199544194944, 0.73965610667174608, 0.71336907999303556, 0.70787383569771856, 0.70322481089044953, 0.71960963710316284, 0.72448633388856543, 0.7321533684342264, 0.73769464468274937, 0.71327142099876828, 0.70234817681809536, 0.74763231367558181, 0.72685450885319691, 0.71115849538767772, 0.70089308730502353, 0.72093756151291921, 0.73035537167339082, 0.7274869207330491, 0.70256570759882686, 0.72981157602588809, 0.72949805848780258, 0.72151470681851015, 0.71307810950918671, 0.73938330325705814, 0.7258310816144985, 0.73569233249685984, 0.73576186558112688, 0.7306642125209889, 0.73589417981474115, 0.73602949409040197, 0.70850981523012757, 0.74729627762917128, 0.73290248315315354, 0.71241695151247264, 0.71223975981197996, 0.73654163227830283, 0.70513346088709328, 0.72800063452082853, 0.71507999921776222, 0.73213334539708064, 0.71739643186705981]