# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [1]:
import os
import numpy as np
import pandas as pd

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [4]:
list1 = [e + 1 for e in range(50)]
list1

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [5]:
list2 = [2*(e+1) for e in range(100)]
list2

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200]

### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [6]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

In [13]:
list3 = [k for e in a for k in e]
list3

[0.84062117,
 0.48006452,
 0.7876326,
 0.77109654,
 0.44409793,
 0.09014516,
 0.81835917,
 0.87645456,
 0.7066597,
 0.09610873,
 0.41247947,
 0.57433389,
 0.29960807,
 0.42315023,
 0.34452557,
 0.4751035,
 0.17003563,
 0.46843998,
 0.92796258,
 0.69814654,
 0.41290051,
 0.19561071,
 0.16284783,
 0.97016248,
 0.71725408,
 0.87702738,
 0.31244595,
 0.76615487,
 0.20754036,
 0.57871812,
 0.07214068,
 0.40356048,
 0.12149553,
 0.53222417,
 0.9976855,
 0.12536346,
 0.80930099,
 0.50962849,
 0.94555126,
 0.33364763]

### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [14]:
list4 = [k for e in a for k in e if k >= 0.5]
list4

[0.84062117,
 0.7876326,
 0.77109654,
 0.81835917,
 0.87645456,
 0.7066597,
 0.57433389,
 0.92796258,
 0.69814654,
 0.97016248,
 0.71725408,
 0.87702738,
 0.76615487,
 0.57871812,
 0.53222417,
 0.9976855,
 0.80930099,
 0.50962849,
 0.94555126]

### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [17]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])

In [20]:
list5 = [j for e in b for k in e for j in k]
list5

[0.55867166,
 0.06210792,
 0.08147297,
 0.82579068,
 0.91512478,
 0.06833034,
 0.05440634,
 0.65857693,
 0.30296619,
 0.06769833,
 0.96031863,
 0.51293743,
 0.09143215,
 0.71893382,
 0.45850679,
 0.58256464,
 0.59005654,
 0.56266457,
 0.71600294,
 0.87392666,
 0.11434044,
 0.8694668,
 0.65669313,
 0.10708681,
 0.07529684,
 0.46470767,
 0.47984544,
 0.65368638,
 0.14901286,
 0.23760688]

### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [28]:
list5 = [j if i==2 and j > 0.5 else j for e in b for (i,k) in enumerate(e) for j in k ]
list5

[0.55867166,
 0.06210792,
 0.08147297,
 0.82579068,
 0.91512478,
 0.06833034,
 0.05440634,
 0.65857693,
 0.30296619,
 0.06769833,
 0.96031863,
 0.51293743,
 0.09143215,
 0.71893382,
 0.45850679,
 0.58256464,
 0.59005654,
 0.56266457,
 0.71600294,
 0.87392666,
 0.11434044,
 0.8694668,
 0.65669313,
 0.10708681,
 0.07529684,
 0.46470767,
 0.47984544,
 0.65368638,
 0.14901286,
 0.23760688]

### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [34]:
import os
list6 = [file for file in os.listdir("../data/") if ".csv" in file]
list6

['sample_file_5.csv',
 'sample_file_0.csv',
 'sample_file_6.csv',
 'sample_file_2.csv',
 'sample_file_1.csv',
 'sample_file_7.csv',
 'sample_file_9.csv',
 'sample_file_3.csv',
 'sample_file_4.csv',
 'sample_file_8.csv']

### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [43]:
import pandas as pd
list7 = [pd.read_csv("../data/" + e) for e in list6]
pd.concat(list7).head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.437114,0.156941,0.183148,0.817785,0.747632,0.726855,0.944758,0.287449,0.792692,0.080025,0.079886,0.067887,0.543498,0.711158,0.960030,0.810807,0.579395,0.660811,0.520295,0.945250
1,0.213337,0.503490,0.802663,0.443484,0.700893,0.129329,0.007176,0.027735,0.427692,0.156926,0.486138,0.571278,0.940414,0.940730,0.933377,0.427869,0.654402,0.407580,0.122453,0.115311
2,0.625692,0.184609,0.120652,0.410955,0.408272,0.686792,0.480168,0.286901,0.320112,0.048815,0.768725,0.461014,0.090451,0.720938,0.192501,0.219077,0.034113,0.858956,0.816036,0.582192
3,0.642007,0.175592,0.476889,0.451096,0.803491,0.272613,0.576037,0.774269,0.323313,0.349850,0.413465,0.641111,0.841210,0.668661,0.101031,0.972135,0.479581,0.149982,0.035150,0.528075
4,0.809129,0.549374,0.055405,0.857802,0.760688,0.662257,0.453289,0.658329,0.973615,0.449771,0.615229,0.467290,0.158077,0.305716,0.730355,0.412336,0.469142,0.078734,0.448741,0.827487
0,0.734751,0.195362,0.734309,0.598184,0.763433,0.263434,0.868066,0.058092,0.753502,0.587513,0.311608,0.178356,0.182922,0.147631,0.391188,0.816049,0.749068,0.293260,0.937828,0.880858
1,0.772607,0.445391,0.249642,0.787922,0.598583,0.827238,0.624126,0.601524,0.688753,0.338870,0.081595,0.471474,0.267443,0.453351,0.800716,0.045749,0.683793,0.389789,0.016787,0.503695
2,0.226428,0.268764,0.694262,0.622335,0.063843,0.122683,0.815625,0.584542,0.032594,0.589775,0.764350,0.650973,0.565705,0.691784,0.265223,0.739031,0.560394,0.334802,0.517694,0.646110
3,0.362748,0.495430,0.113876,0.594149,0.612522,0.625204,0.864050,0.260279,0.528873,0.168043,0.715929,0.677014,0.175735,0.632370,0.926715,0.085675,0.120525,0.141746,0.771144,0.489660
4,0.033415,0.340433,0.464971,0.363737,0.025815,0.434129,0.415163,0.892210,0.381701,0.415264,0.790801,0.696930,0.819751,0.944029,0.869965,0.041723,0.819140,0.676051,0.109349,0.872947

### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [79]:
list8 = [df.keys()[i] for i,e in enumerate(df.mean()) if e > 0.48]
print(list8)

['0', '2', '3', '4', '5', '6', '7', '8', '10', '11', '13', '14', '15', '16', '17', '18', '19']

### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [80]:
df["20"] = [e - 0.1 for e in df["19"]]
df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.437114,0.156941,0.183148,0.817785,0.747632,0.726855,0.944758,0.287449,0.792692,0.080025,...,0.067887,0.543498,0.711158,0.960030,0.810807,0.579395,0.660811,0.520295,0.945250,0.845250
1,0.213337,0.503490,0.802663,0.443484,0.700893,0.129329,0.007176,0.027735,0.427692,0.156926,...,0.571278,0.940414,0.940730,0.933377,0.427869,0.654402,0.407580,0.122453,0.115311,0.015311
2,0.625692,0.184609,0.120652,0.410955,0.408272,0.686792,0.480168,0.286901,0.320112,0.048815,...,0.461014,0.090451,0.720938,0.192501,0.219077,0.034113,0.858956,0.816036,0.582192,0.482192
3,0.642007,0.175592,0.476889,0.451096,0.803491,0.272613,0.576037,0.774269,0.323313,0.349850,...,0.641111,0.841210,0.668661,0.101031,0.972135,0.479581,0.149982,0.035150,0.528075,0.428075
4,0.809129,0.549374,0.055405,0.857802,0.760688,0.662257,0.453289,0.658329,0.973615,0.449771,...,0.467290,0.158077,0.305716,0.730355,0.412336,0.469142,0.078734,0.448741,0.827487,0.727487
0,0.734751,0.195362,0.734309,0.598184,0.763433,0.263434,0.868066,0.058092,0.753502,0.587513,...,0.178356,0.182922,0.147631,0.391188,0.816049,0.749068,0.293260,0.937828,0.880858,0.780858
1,0.772607,0.445391,0.249642,0.787922,0.598583,0.827238,0.624126,0.601524,0.688753,0.338870,...,0.471474,0.267443,0.453351,0.800716,0.045749,0.683793,0.389789,0.016787,0.503695,0.403695
2,0.226428,0.268764,0.694262,0.622335,0.063843,0.122683,0.815625,0.584542,0.032594,0.589775,...,0.650973,0.565705,0.691784,0.265223,0.739031,0.560394,0.334802,0.517694,0.646110,0.546110
3,0.362748,0.495430,0.113876,0.594149,0.612522,0.625204,0.864050,0.260279,0.528873,0.168043,...,0.677014,0.175735,0.632370,0.926715,0.085675,0.120525,0.141746,0.771144,0.489660,0.389660
4,0.033415,0.340433,0.464971,0.363737,0.025815,0.434129,0.415163,0.892210,0.381701,0.415264,...,0.696930,0.819751,0.944029,0.869965,0.041723,0.819140,0.676051,0.109349,0.872947,0.772947

### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.

In [108]:
list10 = [j for e in b for k in e for j in k if j>0.7 and j<0.75]
list10

[0.71893382, 0.71600294]