# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [1]:
import os
import numpy as np
import pandas as pd
import glob

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [2]:
lista=[e for e in range(1,51)]
print (lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [3]:
evenNumbers=[e for e in range(2,201) if e%2==0]
print(evenNumbers)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]

### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [4]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

In [5]:
'''lista_a=np.concatenate(a)
print(lista_a)'''

lista_a=[x for lista in a.tolist() for x in lista]

print(lista_a)

[0.84062117, 0.48006452, 0.7876326, 0.77109654, 0.44409793, 0.09014516, 0.81835917, 0.87645456, 0.7066597, 0.09610873, 0.41247947, 0.57433389, 0.29960807, 0.42315023, 0.34452557, 0.4751035, 0.17003563, 0.46843998, 0.92796258, 0.69814654, 0.41290051, 0.19561071, 0.16284783, 0.97016248, 0.71725408, 0.87702738, 0.31244595, 0.76615487, 0.20754036, 0.57871812, 0.07214068, 0.40356048, 0.12149553, 0.53222417, 0.9976855, 0.12536346, 0.80930099, 0.50962849, 0.94555126, 0.33364763]

### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [6]:
print([e for e in lista_a if e>=0.5])

[0.84062117, 0.7876326, 0.77109654, 0.81835917, 0.87645456, 0.7066597, 0.57433389, 0.92796258, 0.69814654, 0.97016248, 0.71725408, 0.87702738, 0.76615487, 0.57871812, 0.53222417, 0.9976855, 0.80930099, 0.50962849, 0.94555126]

### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [7]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])

In [8]:
lista_b= [e for lista in np.concatenate(b) for e in lista]

print(lista_b)

[0.55867166, 0.06210792, 0.08147297, 0.82579068, 0.91512478, 0.06833034, 0.05440634, 0.65857693, 0.30296619, 0.06769833, 0.96031863, 0.51293743, 0.09143215, 0.71893382, 0.45850679, 0.58256464, 0.59005654, 0.56266457, 0.71600294, 0.87392666, 0.11434044, 0.8694668, 0.65669313, 0.10708681, 0.07529684, 0.46470767, 0.47984544, 0.65368638, 0.14901286, 0.23760688]

### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [9]:
lista_b2=np.concatenate(b)

minimos=[e for e in lista_b2[:,2] if e<=0.5]
print(minimos)

[0.08147297, 0.06833034, 0.30296619, 0.45850679, 0.11434044, 0.10708681, 0.47984544, 0.23760688]

### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [10]:
files=[ file for file in os.listdir("../data") if file.endswith(".csv")]

print (files)

['sample_file_0.csv', 'sample_file_7.csv', 'sample_file_9.csv', 'sample_file_4.csv', 'sample_file_1.csv', 'sample_file_6.csv', 'sample_file_5.csv', 'sample_file_2.csv', 'sample_file_8.csv', 'sample_file_3.csv']

### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [11]:
all_files= glob.glob("../data" + "/*.csv")

concatenado=pd.concat([pd.read_csv(file) for file in all_files])

display(concatenado.iloc[0:10])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.734751,0.195362,0.734309,0.598184,0.763433,0.263434,0.868066,0.058092,0.753502,0.587513,0.311608,0.178356,0.182922,0.147631,0.391188,0.816049,0.749068,0.293260,0.937828,0.880858
1,0.772607,0.445391,0.249642,0.787922,0.598583,0.827238,0.624126,0.601524,0.688753,0.338870,0.081595,0.471474,0.267443,0.453351,0.800716,0.045749,0.683793,0.389789,0.016787,0.503695
2,0.226428,0.268764,0.694262,0.622335,0.063843,0.122683,0.815625,0.584542,0.032594,0.589775,0.764350,0.650973,0.565705,0.691784,0.265223,0.739031,0.560394,0.334802,0.517694,0.646110
3,0.362748,0.495430,0.113876,0.594149,0.612522,0.625204,0.864050,0.260279,0.528873,0.168043,0.715929,0.677014,0.175735,0.632370,0.926715,0.085675,0.120525,0.141746,0.771144,0.489660
4,0.033415,0.340433,0.464971,0.363737,0.025815,0.434129,0.415163,0.892210,0.381701,0.415264,0.790801,0.696930,0.819751,0.944029,0.869965,0.041723,0.819140,0.676051,0.109349,0.872947
0,0.460281,0.308551,0.735894,0.054059,0.593642,0.397679,0.019922,0.855673,0.339445,0.895810,0.832431,0.553308,0.617711,0.841575,0.336094,0.951907,0.050986,0.856135,0.773953,0.295344
1,0.065851,0.736029,0.797730,0.692722,0.167764,0.839756,0.910186,0.643328,0.371559,0.674311,0.424815,0.279397,0.015081,0.788497,0.132391,0.766033,0.708510,0.752866,0.493862,0.577262
2,0.671323,0.747296,0.892328,0.732902,0.065608,0.262364,0.712417,0.764379,0.017461,0.131970,0.649451,0.902157,0.034188,0.840938,0.098536,0.957824,0.566209,0.655947,0.592733,0.002596
3,0.445478,0.523522,0.959355,0.348292,0.761805,0.301391,0.712240,0.945462,0.139241,0.105477,0.889501,0.160828,0.400774,0.770295,0.844655,0.772798,0.584262,0.807400,0.177419,0.926007
4,0.291399,0.551248,0.736542,0.163562,0.451149,0.888938,0.968465,0.396090,0.681679,0.390542,0.030394,0.944077,0.366139,0.078188,0.175482,0.232489,0.806964,0.904593,0.803629,0.792851

### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [12]:
selected_columns = [col for col in concatenado._get_numeric_data() if concatenado[col].median() > 0.48]
print(selected_columns)

['0', '1', '3', '4', '5', '6', '7', '8', '10', '11', '13', '15', '16', '18', '19']

### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [13]:
concatenado["20"] = concatenado["19"] - 0.1
display(concatenado.iloc[0:10])

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.734751,0.195362,0.734309,0.598184,0.763433,0.263434,0.868066,0.058092,0.753502,0.587513,...,0.178356,0.182922,0.147631,0.391188,0.816049,0.749068,0.293260,0.937828,0.880858,0.780858
1,0.772607,0.445391,0.249642,0.787922,0.598583,0.827238,0.624126,0.601524,0.688753,0.338870,...,0.471474,0.267443,0.453351,0.800716,0.045749,0.683793,0.389789,0.016787,0.503695,0.403695
2,0.226428,0.268764,0.694262,0.622335,0.063843,0.122683,0.815625,0.584542,0.032594,0.589775,...,0.650973,0.565705,0.691784,0.265223,0.739031,0.560394,0.334802,0.517694,0.646110,0.546110
3,0.362748,0.495430,0.113876,0.594149,0.612522,0.625204,0.864050,0.260279,0.528873,0.168043,...,0.677014,0.175735,0.632370,0.926715,0.085675,0.120525,0.141746,0.771144,0.489660,0.389660
4,0.033415,0.340433,0.464971,0.363737,0.025815,0.434129,0.415163,0.892210,0.381701,0.415264,...,0.696930,0.819751,0.944029,0.869965,0.041723,0.819140,0.676051,0.109349,0.872947,0.772947
0,0.460281,0.308551,0.735894,0.054059,0.593642,0.397679,0.019922,0.855673,0.339445,0.895810,...,0.553308,0.617711,0.841575,0.336094,0.951907,0.050986,0.856135,0.773953,0.295344,0.195344
1,0.065851,0.736029,0.797730,0.692722,0.167764,0.839756,0.910186,0.643328,0.371559,0.674311,...,0.279397,0.015081,0.788497,0.132391,0.766033,0.708510,0.752866,0.493862,0.577262,0.477262
2,0.671323,0.747296,0.892328,0.732902,0.065608,0.262364,0.712417,0.764379,0.017461,0.131970,...,0.902157,0.034188,0.840938,0.098536,0.957824,0.566209,0.655947,0.592733,0.002596,-0.097404
3,0.445478,0.523522,0.959355,0.348292,0.761805,0.301391,0.712240,0.945462,0.139241,0.105477,...,0.160828,0.400774,0.770295,0.844655,0.772798,0.584262,0.807400,0.177419,0.926007,0.826007
4,0.291399,0.551248,0.736542,0.163562,0.451149,0.888938,0.968465,0.396090,0.681679,0.390542,...,0.944077,0.366139,0.078188,0.175482,0.232489,0.806964,0.904593,0.803629,0.792851,0.692851

### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.

In [14]:
extract = [i for i in concatenado.values.flatten() if i<0.75 and i >0.7]

print(extract)

[0.7347510852128797, 0.7343092314001137, 0.7490680818183477, 0.7390312927111312, 0.7159290265157912, 0.7358941798147411, 0.736029494090402, 0.7085098152301276, 0.7472962776291713, 0.7329024831531535, 0.7124169515124726, 0.71223975981198, 0.7365416322783028, 0.7051334608870933, 0.7280006345208285, 0.7150799992177622, 0.7321333453970806, 0.7173964318670598, 0.7383982036983279, 0.7178166705957928, 0.7088042362916818, 0.7374449181749492, 0.7264121114538001, 0.7133695725698419, 0.7356923324968598, 0.7357618655811269, 0.7306642125209889, 0.7025657075988269, 0.7298115760258881, 0.7294980584878026, 0.7215147068185102, 0.7130781095091867, 0.7393833032570581, 0.7258310816144985, 0.7476323136755818, 0.7268545088531969, 0.7111584953876777, 0.7008930873050235, 0.7209375615129192, 0.7303553716733908, 0.7274869207330491, 0.7033930409580709, 0.7013619954419494, 0.7396561066717461, 0.7133690799930356, 0.7078738356977186, 0.7032248108904495, 0.7196096371031628, 0.7244863338885654, 0.7321533684342264, 0.7376946446827494, 0.7132714209987683, 0.7023481768180954, 0.7045750112959754]